production:
  adapter: postgresql
  encoding: unicode
  host: postgresql7.locum.ru
  database: nerrey_Nerrey49
  username: nerrey_Nerrey49
  password: Aaa14156

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: gcgames
  username: ns
  password: 14156