production:
  adapter: postgresql
  encoding: unicode
  host: postgresql7.locum.ru
  database: nerrey_gcgames64
  username: nerrey_gcgames64
  password: 9zSUKO4UI4

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: gcgames
  username: ns
  password: 14156

test:
  adapter: postgresql
  encoding: unicode
  host: postgresql7.locum.ru
  database: nerrey_gcgames64
  username: nerrey_gcgames64
  password: 9zSUKO4UI4